### ISSUE TITLE
Observation API Specification

### ISSUE THREAD

**Issue by kitsonk** [dojo/stores#1]
Specify the observation API.

Initial recommendation would be something like this:

``` typescript
interface Store {
    observe<T>(id: number): Observable<T>;
}
```

**Comment by kitsonk** [comment]
In addition @kfranqueiro mentioned that we should also have the ability to observe just the store as a whole, meaning individual changes to records should be observed as well.

Are there any other changes that we should be able to observe from stores?

**Comment by dylans** [comment]
I believe this landed a while ago.
