### ISSUE TITLE
IndexedDB should search through all filters to build optimized indices

### ISSUE THREAD

**Issue by maier49** [dojo/stores#105]
Currently, when passed queries, the IndexedDB storage implementation looks at the first queries and determines whether they can be applied to indices in its storage. If they can, then they are, and any subsequent queries are applied either as the resulting cursor is iterated through, or once iteration is complete, based on the type of query.

In some cases though, a user may be searching on multiple indexable fields. In this case, we could get better performance if we searched through all queries, built out as many separate searches as possible, and then combined the results.

**Comment by agubler** [comment]
Closing since the latest version of stores has landed
