### ISSUE TITLE
Main Store Interface

### ISSUE THREAD

**Issue by kitsonk** [dojo/stores#12]
Currently @maier49 is proposing the following _base_ interface for Stores:

``` typescript
export interface Store<T, O> {
    get(ids: string[] | string): Promise<T[]>;
    getIds(items: T[] | T): string[];
    generateId(): Promise<string>;
    add(items: T[] | T, options?: O): StoreObservable<T>;
    put(items: T[] | T, options?: O): StoreObservable<T>;
    patch(updates: Map<string, Patch<T, T>> | { id: string; patch: Patch<T, T> } | { id: string; patch: Patch<T, T> }[], options?: O): StoreObservable<T>;
    delete(ids: string[] | string): StoreObservable<T>;
    observe(): Observable<MultiUpdate<T>>;
    observe(ids: string | string[]): Observable<Update<T>>;
    release(actionManager?: StoreActionManager<T>): Promise<Store<T, O>>;
    track(): Promise<Store<T, O>>;
    fetch(): Promise<T[]>;
    fetch<U>(query: Query<T, U>): Promise<U[]>;
    query(query: Query<T, T>): Store<T, O>;
    filter(filter: Filter<T>): Store<T, O>;
    filter(test: (item: T) => boolean): Store<T, O>;
    createFilter(): Filter<T>;
    range(range: StoreRange<T>): Store<T, O>;
    range(start: number, count: number): Store<T, O>;
    sort(sort: Sort<T> | ((a: T, b: T) => number) | string, descending?: boolean): Store<T, O>;
    transaction(): Transaction<T, O>;
}
```

We should discuss if this is the right interface/design.  My thoughts are:
- `getIds()` - I think the following is better:

``` typescript
identify(items: T): Promise<T>;
identify(items: ArrayLike<T> | Iterable<T>): Promise<string[]>;
```
- Semantically and consistency, would `createId` be better than `generateId`?
- I think for now, we should have `query()` API as a mixin the is not part of the main store, along with it, I think related APIs should be narrowed and not part of the main Store API for now until we figure out if we want a really fat Store API or something relatively narrow.
- We should split transaction off as a separate mixin and not have it be part of the main Store API, even if all of our stores end up supporting it.
- Thinking again out loud, we have several different "categories" of APIs that we should explode out into interfaces, especially if those interfaces don't have a significant amount of co-dependency on each other.  For example, `track` and `release` seem to be separate from the _CRUD_ functions.  `.patch` is part of _CRUD_ but `.observe` either stands on its own, or goes with the `.track()` and `.release()`.  Does `.transaction()` go in that category as well?  Then we have the query stuff...

**Comment by maier49** [comment]
To give an update on this issue. A first pass prototype at splitting up and implementing this API via different mixins can be found [here](https://github.com/maier49/store). In general I think breaking up the API this way has helped clean up the code, allow for better separation of conerns etc. but there is at least one significant challenge to this way of breaking up the API.

The `query()` and `track()`  APIs both result in a new store being returned, that has the same type as the parent store. Individually these accomplish this by returning a generic type and `this` to capture the query or track API respectively as well as the store API with which they have been combined.

``` typescript
interface QueryMixin<T, O extends CrudOptions, U extends UpdateResults<T>, C extends Store<T, O, U>> {
    query(query: Query<T, T>): C & this;
}
```

Individually these work fine, with the caveat that an appropriate interface for the compose factory has to be declared to allow the use of the generics. But when combined this is a problem, as `this` in query and `this` in track don't refer to the same type. Resolving the issue with generics only results in circular definitions, unless there's a clever way of doing it that I'm not seeing, and intersecting the two types doesn't change what `this` refers to in each. The only way I've found to fix it is to declare a new interface that extends both interfaces(as well as the interfaces of any other `this`-returning mixins that are being used), and use that as the type of the resulting store.

``` typescript
interface TrackableObservableQueryStore<T, O extends CrudOptions, U extends UpdateResults<T>> extends
    ObservableStore<T, O, U>,
    SubcollectionStore<T, O, U, ObservableStore<T, O, U>>,
    QueryMixin<T, O, U, ObservableStore<T, O, U>>,
    TrackableMixin<T, O, U, ObservableStore<T, O, U>> {
}
```

This isn't a ton of boilerplate, but I can't imagine anybody would be happy about having to add something like this for each combination of mixins they want to use.

**Comment by kitsonk** [comment]
@maier49 largely though that is what we have been doing in widgets, though it should be noted that TypeScript does not handle overloads well when extending interfaces and therefore we have had to use `type` and the intersection operator.  For example [`createButton`](https://github.com/dojo/widgets/blob/20b08d91da961c57d47df2124c5e5a6afb5c0e12/src/createButton.ts#L11).

There is a bit of a pattern in order to have this done effectively, but the burden is often upon an implementor and the end developer consumer is often abstracted from this behaviour.  If there isn't a need for further downstream re-use, that boilerplate can often be omitted.  For example in `monster-cards` we have eliminated a lot of that because they classes were _final_ and didn't need to be recombined externally. For example [`createNavMenu`](https://github.com/dojo/examples/blob/6a65473d2965730fd17a7a36387f0452c76cd9f8/monster-cards/src/widgets/navbar/createNavMenu.ts) which is totally lacking in boilerplate interfaces.

**Comment by maier49** [comment]
@kitsonk To the point about intersections instead of extending, in this case that doesn't create the needed behavior, as far as I can tell. If I have

``` typescript
interface A {
    a(): this;
}
interface B {
    b(): this;
}

let aAndB: A & B;
let a = aAndB.a(); // Is A
let b = aAndB.b(); // Is B
```

Then `a` will be of type `A` and `b` will be of type `B`
But what I want is for `a` and `b` to both still be `A & B`.  

The comment about having a final class that doesn't need to be recombined externally makes sense, but wouldn't that be essentially changing the store to have a 'fat' interface rather than breaking out the different parts of the interface to separate components?

**Comment by dylans** [comment]
This has been resolved through other tickets and work on stores. Any new feedback or refinements will be handled through new tickets.
