### ISSUE TITLE
status

### ISSUE THREAD

**Issue by xblox** [dojo/stores#122]
Hey guys,

do you have by chance an estimate for a beta? 

I tried to integrate dojo/stores but I failed (I got the other dojo-2 packages working for me). 

And whilst at it: 
1. will dojo/stores be the successor of dstore?, and eventually dmodel?
2. likely on your radar already but just to make sure: can I use dojo/stores for isomorphic code? 

I am just asking because most of my projects rely on dstore and I waiting desperately to start migrating them to Typescript but without a 'store' I won't get far at all.

thanks for any comment on this,
g

**Comment by dylans** [comment]
Hi @xblox,

Our current plans for beta 1 for Dojo 2 are this month, though dojo/stores won't be considered beta until Dojo beta 2 which is planned for May. The main reason for this is that there was a lot of churn with TS finally making mixins and composition possible with classes in TS 2.2, and we still have a fair amount of work in stores to refactor things based on that change. It changes some of our thoughts around what things should be mixins vs. base classes, etc.

dojo/stores is the successor to dstore. dmodel is going to be decided on next month hopefully, when we start determining how state is managed with Dojo 2 apps, among other things. https://github.com/dojo/stores/issues/77 is an open placeholder issue for that eventual discussion.

Yes, dojo/stores should be usable for isomorphic code (that's the intent for all of Dojo 2 except for things that are very browser specific).

I hope this helps.

**Comment by xblox** [comment]
Hey Dylan, thanks a million for the dates and the green light on isomorphic. 
I am fully aware about the difficulties with TS/ES6 in Dojo-2. I'll go for a quick'n dirty TS port for dstore in the meantime instead. 

gonna close this here since my questions are answered,
g

**Comment by xblox** [comment]
Hi,
there were a number of changes, didn't test yet but I go on in assuming this is the replacement for dstore in all my new migrated apps :-)

**Comment by kitsonk** [comment]
@xblox we are still debating if an pure _CRUD_ API like stores is the right pattern for Dojo 2.  Overall, we seem to drawn to more reactive patterns, where there is an inversion of control, and this traditional _store_ model begins to break down.

This is why we haven't been 100% clear on the direction for this.  I do expect that we will be in a position in the next week or so of trying to articulate what we think and _application_ is in the terms of Dojo 2, which will help inform of how a Dojo 2 application would handle data retrieval and persistence.

**Comment by xblox** [comment]
@kitsonk : great; can't wait.

I am looking in the mean-time at RxJS; At the end most of my legacy code (dgrid-1, dstore & dmodel) needs something like a store. There is not much offer at the moment. I understand that you may be drop the whole thing here :-)

g

**Comment by kitsonk** [comment]
We won't drop the "whole thing", but we are potentially considering something that is a bit more concise and focused of an API and would sort of decouple the _two way_ flow of information that occurs with the existing paradigm.  @agubler and @pottedmeat have experimented with a _data provider_ that provides, well data, but doesn't allow you to modify that data.  Whenever, your view of the data, as a consumer, changes, you get the data without having to worry about it, and you simply worry about _rendering_ that data.

The other side, of modifying data, could likely follow the model of sort of reactive state containers like Redux, where actions cause the mutations of the data to occur.

We strongly feel that breaking that 2 way flow makes far more maintainable code and fits better into where Dojo 2 widget include dgrid are headed.
