### ISSUE TITLE
Dojo 2 Stores Proposal/Specification

### ISSUE THREAD

**Issue by kitsonk** [dojo/stores#14]
@kitsonk commented on [Mon Jan 04 2016](https://github.com/dojo/meta/issues/12)
## Story

Dojo 2 needs a full featured persistent storage APIs that make it easy for subscribers to get/set the information relevant to their needs.
## Features

The specification should express several features:
- Embrace TypeScript and typing of data.
- Allow subscribers to retrieve subsets of data, versus whole objects.
- Allow subscribers to receive relevant change records, versus whole objects.
## Considerations

There are several things to consider:
- There is [dojo/dojo/store](https://github.com/dojo/dojo/tree/master/store) and [dstore](https://github.com/SitePen/dstore) as prior art.
- How does GraphQL (or another type of incremental query language) fit into somethings like this?

**Comment by kitsonk** [comment]
We should ensure that we have some sort of formal document for the architecture/API/overview of stores.  This issue can be used to track that.

**Comment by dylans** [comment]
At this point I think the readme covers this. We'll also of course add information to the reference guide.
