### ISSUE TITLE
Typing issue when calling process executor

### ISSUE THREAD

**Issue by agubler** [dojo/stores#146]
**Bug**

During the recent typing enhancement, the process executor `payload` type has been restricted to be the same as the generic type passed to the store during `new Store<MyState>()`, in this example `MyState`. This prevents valid arguments being passed to the executor using `myProcess(store)(argumentOne, argumentTwo)`.

Package Version: 0.2.0

**Code**

```ts
import { Store } from '@dojo/stores/Store';
import { createCommandFactory, createProcess } from '@dojo/stores/process';
import { replace } from '@dojo/stores/state/operations';
import { PatchOperation } from '@dojo/stores/state/Patch';

interface State {
	foo: string;
	bar: {
		baz: boolean;
	};
}

const store = new Store<State>();

const commandFactory = createCommandFactory<State>();

const initialCommand = commandFactory(({ path, get, payload: [ foo, bar ] }): PatchOperation[] => {
	return [
		replace(path('foo'), foo),
		replace(path('bar'), bar)
	];
});

const initialProcess = createProcess([ initialCommand ]);

// Errors expecting a single argument - Processes should be able to take `...args` of any type
initialProcess(store)('foo', { bar: { baz: 'baz' } });
```

**Expected behavior:**

Support passing `n` number of arguments to the initial process that get passes as the `payload: any[]` to the `initialCommand`.

**Actual behavior:**

When there is more than one argument:

    `Expected 0-1 arguments, but got 2.

When there is one argument:

     `Argument of type '"foo"' is not assignable to parameter of type 'State | undefined'.`

**Comment by kitsonk** [comment]
It seems to me that `CommandRequest['payload']` could inferred but also correspond to the type of  arguments passed to the `ProcessExecutor`...

For example a `CommandRequest['payload']` type of `[ string, { baz: boolean } ]` would be used above and the `ProcessExecutor<[ string, { baz: boolean } ]>` would ensure that `initialProcess(store)('foo', { bar: { baz: 'baz' } });` would be valid and type constrained.
