### ISSUE TITLE
StoreContainer paths types do not work as expected for deep objects

### ISSUE THREAD

**Issue by agubler** [dojo/stores#174]
**Bug**

The typings for `StoreContainer`s `paths` property do not work correctly for referencing deep property keys. It seems to be caused by having multiple properties, in this example removing either `b` or `c` from interface `A` resolves the errors.

**Code**

```ts
interface A {
	b: B;
	c: C;
}

interface B {
	c: C;
}

interface C {
	d: D;
}

interface D {
	bar: boolean;
}

// no error
const a: StoreContainerPath<A>[] = [['b']];

// typing error
const b: StoreContainerPath<A>[] = [['c', 'd']];

// typing error
const c: StoreContainerPath<A>[] = [['b', 'c', 'd', 'bar']];

// typing error
const d: StoreContainerPath<A>[] = [['c', 'd', 'bar']];
```

**Comment by denov** [comment]
here's a work around.  `keyof` in  `StoreContainerPath` doesn't seem to get confused if you intersection at least one of the types with `any`
```
interface A {
    b: B;
    c: C & any;
}
```

could somebody enlighten me to why?  i'm new to typescript.
