### ISSUE TITLE
[User Story] Querying Data from Stores

### ISSUE THREAD

**Issue by kitsonk** [dojo/stores#19]
# User Story

Given a store which conforms to the Dojo 2 Stores API, a developer needs to express a subset of the stores objects, retrieve those store objects, work with this subset of data in a similar way of interfacing with the Stores API and receive information when this data changes.
# Considerations

There are several key factors which need to be considered around the Query API:
- _Immutable Results_ - Overall Dojo 2 attempts to promote a one way flow of data in order to reduce complex dependencies.  Therefore the Query API should result in data sets that cannot be written to, the changes reflected in the original source store are reflected in the dataset, but you cannot update an object visible from a query.  There should be meta data though which allows a consumer who has retrieved an object from a query to locate the source store where such mutations can be performed.
- _Domain Specific Languages_ - There should be two distinct domain specific languages available to leverage the Query API:
  - _Declarative_ - This API should use simple JavaScript objects (POJOs) to provide a declarative way of describing a query.  This allows the query to be easily serialisable to and from JSON.  It also allows an easy mechanism for other actors to procedurally generate a query and have it executed by the Query API.
  - _Functional_ - This should have full functional parity with the declarative syntax but be offered up in _chain-able_ functions, so that a developer can build the query incrementally taking advantage of intellisense and robust type validation via TypeScript.  There should also be a mechanism to serialise complete functional queries into the declarative syntax.
- _API Functionality_ - While certain store implementations will support a superset of the Query API, there _must_ be a clearly defined base set of functionality supported by all query implementations.
- _Offloading_ - Query implementations should be aligned to leverage the functionality of the underlying store implementation so that certain aspects of the queries are processed in the most efficient way.  The implementations should also give significant considerations to _pooling_ of aspects of processing.  For example, if two different consumers share part or all of a query, then the same resources should be used where the queries overlap.  Because of the _one way_ nature of the flow of data, it should be achievable to create these common paths.
- _Interaction with `dojo-app`_ - The Query API should work with `dojo-app` to be able to reference more complex objects, like instances of stores, functions, actions and other complex object instances it may need to reference.

**Comment by maier49** [comment]
As far as immutable results are concerned, could this be something provided by a separate mixin? Currently, a query returns another store. From there the user could fetch the data, and then potentially manipulate it. Using an immutable array wouldn't provide much additional protection, as the array is already uniquely generated for each fetch, and whether the array itself is immutable or not won't prevent the user from manipulating the underlying data objects. dstore accomplished protecting the internal data by leveraging dmodel. Obviously this doesn't result in completely immutable data, but it does at least force mutations to go through a specific API. We could instead leverage something like Immutable JS to create immutable records for each data object, but this seems like a lot of overhead and API constraints to force on a user by default.

If you're talking about at the store level, we could potentially make query return a read only store, similar to how `transform` might behave. I would lean towards that being optional, or provided by a separate mixin.

**Comment by maier49** [comment]
This has mostly been resolved by #67 , but that doesn't address the DSL concerns, so I opened a separate issue to track that: #81
