### ISSUE TITLE
[User Story] Materializing Data

### ISSUE THREAD

**Issue by kitsonk** [dojo/stores#21]
# User Story

Having a set of data, from a store, query or transformation, a developer will need to materialize this data in a location.  This functionality encapsulates the process of introspecting objects in the target store and determining what mutations if any that are required to materialize the data.  This also implies an ability to express logic around resolving conflicts.

To contextualise this functionality better, consider a todo application.  The developer would have already at this point queried the appropriate business object representations of each todo item and would have applied a transformation to them to change the shape to the appropriate values needed to represent that as a todo item widget state object.  Now the developer needs to:
- Identify which store contains the widget states
- Express logic on what to do if the identity is not present in the state store, which would include instructing a `dojo-app` instance to create and register a new widget instance and to append that widget instance to a parent todo item list.
- Express logic on what to do if an identity is being deleted and any cleanup items
- Potentially express logic on how to _patch_ an existing widget state
# Considerations

There are several key factors that need to be considered around the Materialization API:
- _Results_ - Unlike the Query and Transformation API, the results of the Materialization API are CRUD operations to be performed against a store.
- _API Functionality_ - Instead of being feature rich and expressive, like the Query and Transformation, the Materialization API is essentially a set of functions which aid a developer in being able to deal with identifying and encapsulating CRUD operations given a source and destination set of data.
- _Co-dependency_ - Consideration should be given to how to deal with co-dependency of materialisation.  For example, being able to express that both the creation of the a widget state, the creation of a widget instance and adding the widget as a child of a parent must all be successful for the materialisation to be successful.
- _Diagnostics_ - It is likely, for debugging and development purposes, the ability to get detailed diagnostics of what is occurring during the materialisation would be required.

**Comment by maier49** [comment]
I'm wondering if this needs to be a separate API, or if these goals could be better accomplished by the `query` and `transform` pipeline, and the `observation` API. 
- Identify which store contains the widget states

Currently stores created from the `createSubcollectionStore` base internally keep track of a `source` pointing, to the originating store. By exposing this property to the user, they would be able to determine where the transformed/queried data originally came from.

Right now a series of queries, and presumably a series of transformations, will still result in `source` pointing to the original store that the sequence of queries/transformations was applied to. If at any point in the chain, a store should 'break off', and become a separate source of data on its own, this can be accomplished via the `createTrackableMixin`. If this functionality is needed frequently enough it could always be rolled into the `createSubcollectionStore`.
- Express logic on what to do if the identity is not present in the state store, which would include instructing a `dojo-app` instance to create and register a new widget instance and to append that widget instance to a parent todo item list.

The discovery that an identity is not present in the state store could happen in multiple ways. A `get` or `fetch` could return an empty result set, or a `put` with `rejectOverwrite` set to true in its options argument could return false. In the `get` and `fetch` cases, the store would not, at that time, have the necessary information to create create the item. So by telling the store how to create the missing item we really wouldn't be removing the burden of knowing how to do that from whoever is interacting with the store's API. Maybe I'm missing something, but it seems like having proper logic in place for handling a failed `put` and `get` and `fetch` cases, and taking the proper action as a result should be the responsibility of the store consumer. Of course, the store could facilitate that by providing access to the relevant `source` collection.
- Express logic on what to do if an identity is being deleted and any cleanup items
  Again I would lean towards this being the responsibility of the application. We are providing store-wide and item specific observables, and those seem to me like the right place to hook into a store to do this kind of post delete cleanup.
- Potentially express logic on how to _patch_ an existing widget state
  I think this could be accomplished via access to the `source` store, and the ability to do perform a `put` or `patch` operation there. I think it could also be aided by having an optional two way binding between a transformed store and its source. That depends on the transformation API supporting that of course.
