### ISSUE TITLE
Partials

### ISSUE THREAD

**Issue by kitsonk** [dojo/stores#6]
Stores should support the concept of partials.

**Comment by kfranqueiro** [comment]
What does this mean, exactly?  Is this referring to partial objects or something else?

**Comment by kitsonk** [comment]
This is an "Epic" on ZenHub, it currently has two detailed issues it owns.  So this expresses the high level feature of which the details of how we support it are starting to be dealt with in #4 and #5.

**Comment by agubler** [comment]
Closing since the latest version of stores has landed
